/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku_desktop;

import javax.swing.JLabel;

/**
 *
 * @author Nasko_Nastolen
 */
public class Clock extends JLabel implements Runnable {

    private Time time;
    private Thread t;
    private volatile boolean suspended;
    private volatile boolean stopped;
    
    public Clock()
    {
//        initComponents();
        time = new Time();
        t = new Thread(this);
        suspended = false;
        stopped = false;
    }
    
    public Clock(int seconds)
    {
        time = new Time(seconds);
        t = new Thread(this);
        suspended = false;
        stopped = false;
//        t.start();
    }
    
//    public void setClock(Time newTime)
//    {
//        time.setTime(newTime);
//    }
    
    public void run()
    {
        do
        {
            try
            {
                Thread.sleep(1000);
                time.makeTick();
//                setLblClockDisplay();
                setText(time.getTimeInHMS());
                synchronized(this)
                {
                    while(suspended)
                    {
                        wait();
                    }
                    if(stopped)
                        break;
                }
            }
            catch (InterruptedException ex)
            {
                ex.printStackTrace();
            }
        }
        while(true);
        
    }
    
//    private synchronized void setLblClockDisplay()
//    {
//        lblClockDisplay.setText(time.toString());
//    }
    
    public void startClock()
    {
//        time.setCurrentTime();
        /*stopped = false;
        suspended = false;*/
        t.start();
//        suspended = false;
    }
    
    public synchronized void suspendClock()
    {
//        t.stop();
        suspended = true;
    }

    public synchronized void resumeClock()
    {
//        t.stop();
        suspended = false;
        notify();
    }
    
    public synchronized void resumeClock(int seconds)
    {
//        t.stop();
        time.setSeconds(seconds);
        suspended = false;
        notify();
    }
    public synchronized void stopClock()
    {
//        t.stop();
        stopped = true;
        suspended = false;
        notify();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        
//        lblClockDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//
//    }// </editor-fold>                        

//private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {                                         
//    startClock();
//}                                        
//
//private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {                                        
//    stopClock();
//}                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Clock().setVisible(true);
            }
        });
        /*Clock c = new Clock();
        c.setVisible(true);*/
    }
    // Variables declaration - do not modify                     
//    private javax.swing.JButton btnStart;
//    private javax.swing.JButton btnStop;
//    private javax.swing.JLabel lblClockDisplay;
    // End of variables declaration                   
}