/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku_desktop;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.WindowConstants;

/**
 *
 * @author Nasko_Nastolen
 */
public class SudokuCells extends javax.swing.JPanel {

    /**
     * Creates new form SudokuCells
     */
    private JLabel[][] cell;
    /*private final Color DEFAULT_BACKGROUND;
    private final Font DEFAULT_FONT;
    private final Dimension DEFAULT_DIMENSION;*/
    public SudokuCells() {
        /*cell = new JLabel[9][9];
        //this.setPreferredSize(new Dimension(300, 300));
        //initComponents();
        DEFAULT_BACKGROUND = new Color(255, 255, 255);
        DEFAULT_FONT = new Font("Calibri", 0, 17);
        DEFAULT_DIMENSION = new Dimension(32, 32);
        GridLayout layout = new GridLayout(9, 9);
        final JLabel temp = new JLabel();
        for(int i = 0; i < 9; i++)
            for(int j = 0; j < 9; j++)
            {
                cell[i][j] = new JLabel();
                cell[i][j].setBackground(DEFAULT_BACKGROUND);
                cell[i][j].setFont(DEFAULT_FONT); // NOI18N
                cell[i][j].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                cell[i][j].setVerticalAlignment(javax.swing.SwingConstants.CENTER);
                cell[i][j].setOpaque(true);
                cell[i][j].setPreferredSize(DEFAULT_DIMENSION);
                cell[i][j].setText("5");
                //temp = ;
                final int temp1 = i;
                final int temp2 = j;
                cell[i][j].addMouseListener(new MouseAdapter() {
                    public void mousePressed(MouseEvent e)
                    {
                        cell[temp1][temp2].setText("8");
                        cell[temp1][temp2].setBackground(new Color(213, 215, 32));
                    }
                });
                add(cell[i][j]);
            }*/
        initComponents();
    }
    
    /*public void clearBoard()
    {
        for(int i = 0; i < 9; i++)
            for(int j = 0; j < 9; j++)
            {
                cell[i][j].setText("");
                cell[i][j].setBackground(DEFAULT_BACKGROUND);
            }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new java.awt.GridLayout(9, 9));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("Zdrasti");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
public static void main(String[] args)
{
     SudokuCells c = new SudokuCells();
     JFrame k = new JFrame();
     k.add(c);
     k.setPreferredSize(new Dimension(300,300));
     k.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
     k.setVisible(true);
     c.setVisible(true);
     //k.setBackground(new Color(212, 123, 24, 21));
}

}
